name: Deploy to Azure

# Workflow for deploying Python app to Azure
on:
  push:
    branches:
      - main
  workflow_dispatch:

env:
  AZURE_WEBAPP_NAME: pdf-processor-app
  PYTHON_VERSION: '3.11'

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    
    steps:
    - uses: actions/checkout@v2

    - name: Debug Repository State
      run: |
        echo "Current location:"
        pwd
        echo "\nRepository contents:"
        ls -la
        echo "\nFull directory tree:"
        find . -type f
        echo "\nTests directory specific:"
        ls -la tests/
        echo "\nTest file contents:"
        cat tests/test_simple.py

    - name: Set up Python
      uses: actions/setup-python@v2
      with:
        python-version: ${{ env.PYTHON_VERSION }}

    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install pytest pytest-env pytest-cov
        pip install azure-storage-blob sqlalchemy psycopg2-binary python-dotenv pydantic pydantic-settings
        pip install -r requirements.txt

    - name: Run Tests
      env:
        AZURE_STORAGE_CONNECTION_STRING: ${{ secrets.AZURE_STORAGE_CONNECTION_STRING }}
        AZURE_STORAGE_CONTAINER_NAME: pdf-files
        POSTGRES_USER: ${{ secrets.POSTGRES_USER }}
        POSTGRES_PASSWORD: ${{ secrets.POSTGRES_PASSWORD }}
        POSTGRES_HOST: ${{ secrets.POSTGRES_HOST }}
        POSTGRES_DB: ${{ secrets.POSTGRES_DB }}
        POSTGRES_PORT: "5432"
        PYTHONPATH: ${{ github.workspace }}
      run: |
        echo "Environment setup:"
        python -c "
        import os
        print('\nEnvironment variables:')
        for k, v in os.environ.items():
            if any(x in k for x in ['POSTGRES_', 'AZURE_']):
                print(f'{k}={v if not k.endswith(\"PASSWORD\") else \"***\"}')
        "
        echo "\nRunning tests:"
        python -m pytest -v --tb=short

    - name: Deploy to Azure Web App
      uses: azure/webapps-deploy@v2
      with:
        app-name: ${{ env.AZURE_WEBAPP_NAME }}
        publish-profile: ${{ secrets.AZURE_WEBAPP_PUBLISH_PROFILE }}
        package: . 